<?php
/**
 * TL_ROOT/system/modules/galerie/languages/de/modules.php 
 * 
 * Contao extension: galerie 1.4.0 stable 
 * German translation file 
 * 
 * Copyright : Lionel Maccaud 
 * License   : MIT 
 * Author    : Lionel Maccaud (lionel), http://www.synergie-consulting.com/ 
 * Translator: Carolina Koehn (lucina), http://kikmedia.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['galerie']['0'] = "Galleria";
$GLOBALS['TL_LANG']['MOD']['galerie']['1'] = "Professionelle Bildergalerien für Desktop und mobile Geräte.";
$GLOBALS['TL_LANG']['FMD']['galerie']['0'] = "Galleria";
$GLOBALS['TL_LANG']['FMD']['galerie']['1'] = "Professionelle Bildergalerien für Desktop und mobile Geräte.";
 
?>
